### ISSUE TITLE
Useless queries when primary key is unset

### ISSUE THREAD

**Issue by fabiofdsantos** [jeremyharris/cakephp-lazyload#26]
It generates useless queries to the database.

For example, if `Orders.id` is unset:

```
SELECT ...
FROM orders Orders 
LEFT JOIN delivery_orders DeliveryOrders ON DeliveryOrders.id = (Orders.delivery_order_id) 
WHERE (Orders.id IN (NULL) AND Orders.deleted IS NULL)
```

**Comment by jeremyharris** [comment]
Would you be able to provide a small test case that replicates this issue? It's likely not an issue with this plugin but with the underlying method in the Cake ORM, but I can see if I can try to mitigate it.

**Comment by fabiofdsantos** [comment]
@jeremyharris

I think we just need to replace: https://github.com/jeremyharris/cakephp-lazyload/blob/1319c1ff51476176f5b7d0231c0970085be9cbd3/src/ORM/LazyLoadEntityTrait.php#L131


With:

```php
if ($association === null || $this->get($association->getBindingKey()) === null) {
    return null;
}
```

If you agree, I will open a PR.

**Comment by jeremyharris** [comment]
I think `$this->get($this->getPrimaryKey()) === null` will suffice and is a little more clear. This could be at the very top of `_lazyLoad` as it can't really lazy load data if the PK is missing.

Feel free to open a PR! I appreciate it. Tests are required but if you aren't able to add one I'll take care of it.

**Comment by fabiofdsantos** [comment]
I prefer `$this->get($association->getBindingKey())` because you can assign an id e.g. `$article->authod_id = 123` and then use the lazy load feature.

Feel free to review the PR. Many thanks!
