### ISSUE TITLE
No support for get() method

### ISSUE THREAD

**Issue by robertpustulka** [jeremyharris/cakephp-lazyload#8]
A trait seems to be overloading `__get()` magic method which is just a wrapper for `get()` method.

So... lazy loading through `$entity->property` works but it doesn't work with `$entity->get('property')` which is weird.

I think this should be fixed unless it is done like that intentionally (although I couldn't figure out why).

**Comment by jeremyharris** [comment]
Thanks for reporting! I'll get on this in a couple of weeks when I get back from vacation :)

**Comment by robertpustulka** [comment]
Thanks!

**Comment by jeremyharris** [comment]
No problem. It's not in a release yet, but you can use it with `dev-master`.
